### ISSUE TITLE
点击在线视频或者直播就闪退报错如下：

### ISSUE THREAD

**Issue by DjTenacity** [curtis2/SuperVideoPlayer#21]
com.elliott.supervideoplayer W/IInputConnectionWrapper: reportFullscreenMode on inexistent InputConnection

没有本地视频的一栏，是因为我的手机是7.0的缘故么？？？

**Comment by DjTenacity** [comment]
Error loading libs
                                                                                     java.lang.UnsatisfiedLinkError: Expecting an absolute path of the library: libstlport_shared.so
                                                                                         at java.lang.Runtime.load0(Runtime.java:906)
                                                                                         at java.lang.System.load(System.java:1508)
                                                                                         at io.vov.vitamio.MediaPlayer.load_lib(MediaPlayer.java:258)
                                                                                         at io.vov.vitamio.MediaPlayer.<clinit>(MediaPlayer.java:319)
                                                                                         at io.vov.vitamio.widget.VideoView.openVideo(VideoView.java:432)
